version: "3.9"

services:
  LawOrderPostgres:
    restart: always
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: laworder
      POSTGRES_PASSWORD: laworder
      POSTGRES_DB: law_order
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  LawOrder:
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "9001:9000"
    depends_on:
      - LawOrderPostgres
    environment:
      <<: *environment-defaults
    volumes:
      - /home/projects/SAVE:/yt/news/SAVE
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - static_volume:/yt/static
    env_file:
      - .env
  LawOrderNginx:
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/certificates:/etc/letsencrypt
      - ./docker/nginx/challenges:/var/www/html
      - static_volume:/yt/static
    ports:
      - "81:80"
      - "444:443"
    depends_on:
      - LawOrder

volumes:
    postgres_data:
    static_volume:
    # media_volume:
    nginx_volume: